# Generated by Django 4.2.28 on 2026-02-27 00:44

# Django
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

# Alliance Auth AFAT
import afat.models.afat


class Migration(migrations.Migration):

    replaces = [
        ("afat", "0001_initial"),
        ("afat", "0002_manualfat"),
        ("afat", "0003_auto_20180911_0831"),
        ("afat", "0004_clickfatduration"),
        ("afat", "0005_auto_20200816_2042"),
        ("afat", "0006_auto_20200820_2013"),
        ("afat", "0007_auto_20200826_1537"),
        ("afat", "0008_auto_20200912_1116"),
        ("afat", "0009_auto_20200925_2206"),
        ("afat", "0010_permissoins_update_20201002_1909"),
        ("afat", "0011_change_meta_options_on_manualafat_20201003_2222"),
        ("afat", "0012_manualafat_created_at"),
        ("afat", "0013_basic_module_access_permissions"),
        ("afat", "0014_auto_20201224_0930"),
        ("afat", "0015_afatlink_character"),
        ("afat", "0016_permissions_overhaul"),
        ("afat", "0017_remove_soft_deletion"),
        ("afat", "0018_auto_20210420_2016"),
        ("afat", "0019_add_several_indices"),
        ("afat", "0020_auto_20210617_1037"),
        ("afat", "0021_alter_afatlink_fleet"),
        ("afat", "0022_afatlink_esi_error_count"),
        ("afat", "0023_the_big_rename"),
        ("afat", "0024_setting_doctrine_and_fleet_type"),
        ("afat", "0025_fat_alliance_eve_id_fat_corporation_eve_id"),
        ("afat", "0026_fatsintimefilter"),
        ("afat", "0027_alter_fatlink_last_esi_error"),
        ("afat", "0028_alter_fatsintimefilter_ship_classes"),
    ]

    initial = True

    dependencies = [
        ("eve_sde", "0012_alter_constellation_region"),
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "AFAT",
                "permissions": (
                    ("basic_access", "Can access the AFAT module"),
                    ("manage_afat", "Can manage the AFAT module"),
                    ("add_fatlink", "Can create FAT links"),
                    ("stats_corporation_own", "Can see own corporation statistics"),
                    (
                        "stats_corporation_other",
                        "Can see statistics of other corporations",
                    ),
                    ("log_view", "Can view the modules log"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Doctrine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short name to identify this doctrine",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="You can add notes about this doctrine here if you want. (optional)",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this doctrine is enabled or not.",
                        verbose_name="Is enabled",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctrine",
                "verbose_name_plural": "Doctrines",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="FleetType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name of the fleet type", max_length=254
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this fleet type is active or not",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fleet type",
                "verbose_name_plural": "Fleet types",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_fatlink_expiry_time",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Default expiry time for clickable FAT links in minutes. (Default: 60 minutes)",
                        verbose_name="Default FAT link expiry time",
                    ),
                ),
                (
                    "default_fatlink_reopen_grace_time",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Default time in minutes a FAT link can be re-opened after it is expired. (Default: 60 minutes)",
                        verbose_name="Default FAT link reopen grace time",
                    ),
                ),
                (
                    "default_fatlink_reopen_duration",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Default time in minutes a FAT link is re-opened for. (Default: 60 minutes)",
                        verbose_name="Default FAT link reopen duration",
                    ),
                ),
                (
                    "default_log_duration",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Default time in days a log entry is kept. (Default: 60 days)",
                        verbose_name="Default log duration",
                    ),
                ),
                (
                    "use_doctrines_from_fittings_module",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether to use the doctrines from the Fittings modules in the doctrine dropdown. Note: The fittings module needs to be installed for this.",
                        verbose_name="Use doctrines from fittings module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "log_event",
                    models.CharField(
                        choices=[
                            ("CR_FAT_LINK", "FAT link created"),
                            ("CH_FAT_LINK", "FAT link changed"),
                            ("RM_FAT_LINK", "FAT link removed"),
                            ("RO_FAT_LINK", "FAT link re-opened"),
                            ("RM_FAT", "FAT removed"),
                            ("CR_FAT_MAN", "Manual FAT added"),
                        ],
                        default="CR_FAT_LINK",
                        max_length=11,
                    ),
                ),
                ("log_text", models.TextField()),
                ("fatlink_hash", models.CharField(max_length=254)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=models.SET(afat.models.afat.get_sentinel_user),
                        related_name="afat_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="FatsInTimeFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The filter name that is shown to the admin.",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The filter description that is shown to end users.",
                        max_length=500,
                    ),
                ),
                (
                    "days",
                    models.IntegerField(
                        default=30,
                        help_text="The number of days to look back for FATs.",
                    ),
                ),
                (
                    "fats_needed",
                    models.IntegerField(
                        default=10,
                        help_text="The number of FATs needed to pass the filter.",
                    ),
                ),
                (
                    "fleet_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Any of the selected fleet types are needed to pass the filter.",
                        to="afat.fleettype",
                    ),
                ),
                (
                    "ship_classes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Any of the selected ship classes are needed to pass the filter.",
                        limit_choices_to={"group__category_id": 6},
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Filter: FATs in time period",
                "verbose_name_plural": "Smart Filter: FATs in time period",
            },
        ),
        migrations.CreateModel(
            name="FatLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When was this FAT link created",
                    ),
                ),
                (
                    "fleet",
                    models.CharField(
                        default=None,
                        help_text="The FAT link fleet name",
                        max_length=254,
                    ),
                ),
                (
                    "hash",
                    models.CharField(
                        db_index=True,
                        help_text="The FAT link hash",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "fleet_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The FAT link fleet type, if it's set",
                        max_length=254,
                    ),
                ),
                (
                    "doctrine",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The FAT link doctrine",
                        max_length=254,
                    ),
                ),
                (
                    "is_esilink",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this FAT link was created via ESI or not",
                    ),
                ),
                (
                    "is_registered_on_esi",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the fleet to this FAT link is available in ESI or not",
                    ),
                ),
                ("esi_fleet_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "reopened",
                    models.BooleanField(
                        default=False, help_text="Has this FAT link being re-opened?"
                    ),
                ),
                (
                    "last_esi_error",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "NOT_IN_FLEET",
                                "FC is not in the registered fleet anymore or fleet is no longer available.",
                            ),
                            (
                                "NO_FLEET",
                                "Registered fleet seems to be no longer available.",
                            ),
                            ("NOT_FLEETBOSS", "FC is no longer the fleet boss."),
                            ("FC_WRONG_FLEET", "FC switched to another fleet."),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
                (
                    "last_esi_error_time",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("esi_error_count", models.IntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        default=None,
                        help_text="Character this FAT link has been created with",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Who created the FAT link?",
                        on_delete=models.SET(afat.models.afat.get_sentinel_user),
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link_type",
                    models.ForeignKey(
                        help_text="Deprecated setting, will be removed in a future version …",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="afat.fleettype",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAT link",
                "verbose_name_plural": "FAT links",
                "ordering": ("-created",),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Duration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.PositiveIntegerField()),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duration",
                        to="afat.fatlink",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAT link duration",
                "verbose_name_plural": "FAT link durations",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Fat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "corporation_eve_id",
                    models.BigIntegerField(
                        help_text="Corporation EVE ID of the character who registered this FAT at the time of registration",
                        null=True,
                    ),
                ),
                (
                    "alliance_eve_id",
                    models.BigIntegerField(
                        help_text="Alliance EVE ID of the character who registered this FAT at the time of registration",
                        null=True,
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="The system the character is in",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "shiptype",
                    models.CharField(
                        db_index=True,
                        help_text="The ship the character was flying",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="Character who registered this FAT",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="afat_fats",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "fatlink",
                    models.ForeignKey(
                        help_text="The FAT link the character registered at",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="afat_fats",
                        to="afat.fatlink",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAT",
                "verbose_name_plural": "FATs",
                "default_permissions": (),
                "unique_together": {("character", "fatlink")},
            },
        ),
    ]
