# Generated by Django 5.2.13 on 2026-04-26 08:39

# Django
import django.db.models.deletion
from django.db import migrations, models


def _on_migrate_sde_relationships(apps, schema_editor) -> None:
    """
    Combined data migration to populate the 'ship' and 'solar_system' fields in the Fat
    model based on the existing 'shiptype' and 'system' fields respectively.

    This processes all Fat records once, using in-memory caches for lookups into the
    SDE models to avoid repeated DB queries for the same names.
    """

    DB_CHUNK_SIZE = 1000  # Number of records to process in each bulk operation

    fat_model = apps.get_model("afat", "Fat")
    item_type_model = apps.get_model("eve_sde", "ItemType")
    solar_system_model = apps.get_model("eve_sde", "SolarSystem")
    db_alias = schema_editor.connection.alias
    fats = fat_model.objects.using(db_alias).all()
    tmp_item_type_cache = {}
    tmp_solar_system_cache = {}

    print("\n\nStarting data migration for SDE relationships (ships & solar systems)…")
    print(f"Total FAT records to process: {fats.count()}")

    # Collect objects to bulk update/delete to avoid one-by-one DB operations.
    to_update = []
    to_delete_ids = []

    for fat in fats:
        changed = False
        delete = False

        # Migrate ship relation from shiptype
        if fat.shiptype:
            try:
                if fat.shiptype not in tmp_item_type_cache:
                    item_type = (
                        item_type_model.objects.using(db_alias)
                        .filter(published=True)
                        .get(name=fat.shiptype)
                    )
                    tmp_item_type_cache[fat.shiptype] = item_type

                    print("Fat shiptype:", fat.shiptype)
                    print("Item type:", item_type)

                print("Cached item type:", tmp_item_type_cache[fat.shiptype])

                fat.ship = tmp_item_type_cache[fat.shiptype]
                changed = True
            except item_type_model.DoesNotExist:
                print(
                    f"Warning: ItemType with name '{fat.shiptype}' does not exist. Skipping ship assignment for FAT record with ID {fat.id}."
                )

                delete = True

        # Migrate solar_system relation from system
        if fat.system:
            try:
                if fat.system not in tmp_solar_system_cache:
                    solar_system = solar_system_model.objects.using(db_alias).get(
                        name=fat.system
                    )
                    tmp_solar_system_cache[fat.system] = solar_system

                    print("Fat system:", fat.system)
                    print("Solar system:", solar_system)

                print("Cached solar system:", tmp_solar_system_cache[fat.system])

                fat.solar_system = tmp_solar_system_cache[fat.system]
                changed = True
            except solar_system_model.DoesNotExist:
                print(
                    f"Warning: SolarSystem with name '{fat.system}' does not exist. Skipping solar_system assignment for FAT record with ID {fat.id}."
                )

                delete = True

        if delete:
            print(
                "Scheduling FAT record for deletion due to data inconsistencies:", fat
            )
            to_delete_ids.append(fat.id)

        # Only schedule the instance for update when we've changed fields and are NOT deleting it.
        if changed and not delete:
            print(
                f"Scheduling FAT record for update with ID {fat.id} (ship: {fat.ship}, solar_system: {fat.solar_system})"
            )

            to_update.append(fat)

    # Perform bulk operations in chunks to limit memory/DB load.
    def _chunks(seq, size):
        for i in range(0, len(seq), size):
            yield seq[i : i + size]

    # Bulk update in chunks of DB_CHUNK_SIZE
    updated_count = 0
    for chunk in _chunks(to_update, DB_CHUNK_SIZE):
        # Use the same DB alias for the bulk operation
        fat_model.objects.using(db_alias).bulk_update(
            chunk, ["ship", "solar_system"], batch_size=DB_CHUNK_SIZE
        )
        updated_count += len(chunk)

    # Bulk delete in chunks of DB_CHUNK_SIZE
    deleted_count = 0
    for chunk_ids in _chunks(to_delete_ids, DB_CHUNK_SIZE):
        fat_model.objects.using(db_alias).filter(id__in=chunk_ids).delete()
        deleted_count += len(chunk_ids)

    print(f"Bulk update completed. Updated: {updated_count}, Deleted: {deleted_count}")

    print("Data migration for ships and solar systems completed.\n\n")


class Migration(migrations.Migration):

    dependencies = [
        ("afat", "0001_initialize"),
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fat",
            name="ship",
            field=models.ForeignKey(
                help_text="The ship the character was flying",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AddField(
            model_name="fat",
            name="solar_system",
            field=models.ForeignKey(
                help_text="The system the character is in",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eve_sde.solarsystem",
            ),
        ),
        migrations.AlterField(
            model_name="fat",
            name="fatlink",
            field=models.ForeignKey(
                help_text="The FAT link the character registered with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="afat_fats",
                to="afat.fatlink",
            ),
        ),
        migrations.RunPython(
            code=_on_migrate_sde_relationships,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
