# Generated by Django 5.2.15 on 2026-07-07 09:57

# Django
from django.db import migrations, models

# Alliance Auth
import allianceauth.framework.api.user


class Migration(migrations.Migration):

    dependencies = [
        ("afat", "0002_use_sde_for_fats"),
        ("authentication", "0026_alter_characterownership_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatlink",
            name="creator",
            field=models.ForeignKey(
                help_text="Who created the FAT link?",
                on_delete=models.SET(allianceauth.framework.api.user.get_sentinel_user),
                related_name="+",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=models.SET(allianceauth.framework.api.user.get_sentinel_user),
                related_name="afat_log",
                to="authentication.user",
            ),
        ),
    ]
