# Generated by Django 4.0.10 on 2023-04-17 15:29

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afat", "0021_alter_afatlink_fleet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="afatlink",
            name="is_registered_on_esi",
            field=models.BooleanField(
                default=False,
                help_text="Whether the fleet to this FAT link is available in ESI or not",
            ),
        ),
    ]
