# Generated by Django 4.0.10 on 2023-09-22 08:16

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("afat", "0023_rename_afat_fat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fat",
            name="afatlink",
            field=models.ForeignKey(
                help_text="The FAT link the character registered at",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="afat_fats",
                to="afat.afatlink",
            ),
        ),
        migrations.AlterField(
            model_name="fat",
            name="character",
            field=models.ForeignKey(
                help_text="Character who registered this FAT",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="afat_fats",
                to="eveonline.evecharacter",
            ),
        ),
    ]
