# Generated by Django 4.0.10 on 2023-09-22 08:44

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afat", "0024_alter_fat_afatlink_alter_fat_character"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AFatLinkType",
            new_name="FleetType",
        ),
    ]
