# Generated by Django 4.2.16 on 2024-11-08 19:45

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afat", "0024_doctrines_and_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="default_fatlink_expiry_time",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Default expiry time for clickable FAT links in minutes. (Default: 60 minutes)",
                verbose_name="Default FAT link expiry time",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="default_fatlink_reopen_duration",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Default time in minutes a FAT link is re-opened for. (Default: 60 minutes)",
                verbose_name="Default FAT link reopen duration",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="default_fatlink_reopen_grace_time",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Default time in minutes a FAT link can be re-opened after it is expired. (Default: 60 minutes)",
                verbose_name="Default FAT link reopen grace time",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="default_log_duration",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Default time in days a log entry is kept. (Default: 60 days)",
                verbose_name="Default log duration",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="use_doctrines_from_fittings_module",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether to use the doctrines from the Fittings modules in the doctrine dropdown. Note: The fittings module needs to be installed for this.",
                verbose_name="Use doctrines from fittings module",
            ),
        ),
    ]
