# Generated by Django 4.2.16 on 2024-11-09 13:41

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afat", "0025_setting_default_fatlink_expiry_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatlink",
            name="fleet_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The FAT link fleet type, if it's set",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="fatlink",
            name="link_type",
            field=models.ForeignKey(
                help_text="Deprecated setting, will be removed in a future version …",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="afat.fleettype",
            ),
        ),
    ]
