# Generated by Django 4.2.21 on 2025-05-18 06:28

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afat", "0025_fat_alliance_eve_id_fat_corporation_eve_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatsInTimeFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The filter name that is shown to the admin.",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The filter description that is shown to end users.",
                        max_length=500,
                    ),
                ),
                ("days", models.IntegerField(default=30)),
                ("fats_needed", models.IntegerField(default=10)),
                (
                    "fleet_types",
                    models.ManyToManyField(blank=True, to="afat.fleettype"),
                ),
            ],
            options={
                "verbose_name": "Smart Filter: FATs in time period",
                "verbose_name_plural": "Smart Filter: FATs in time period",
            },
        ),
    ]
