# Generated by Django 4.0.10 on 2023-09-22 08:52

# Django
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("afat", "0026_alter_fleettype_options_alter_fleettype_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AFatLog",
            new_name="Log",
        ),
    ]
