# Generated by Django 4.2.28 on 2026-02-26 23:55

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0012_alter_constellation_region"),
        ("afat", "0027_alter_fatlink_last_esi_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatsintimefilter",
            name="ship_classes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Any of the selected ship classes are needed to pass the filter.",
                limit_choices_to={"group__category_id": 6},
                to="eve_sde.itemtype",
            ),
        ),
    ]
