# Generated by Django 4.0.10 on 2023-09-22 08:53

# Django
from django.conf import settings
from django.db import migrations, models

# Alliance Auth AFAT
import afat.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("afat", "0027_rename_afatlog_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=models.SET(afat.models.get_sentinel_user),
                related_name="afat_log",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
