# Generated by Django 4.0.10 on 2023-09-22 08:53

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afat", "0028_alter_log_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={
                "default_permissions": (),
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
            },
        ),
    ]
