# Generated by Django 4.0.10 on 2023-09-22 08:57

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afat", "0029_alter_log_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="log_event",
            field=models.CharField(
                choices=[
                    ("CR_FAT_LINK", "FAT link created"),
                    ("CH_FAT_LINK", "FAT link changed"),
                    ("RM_FAT_LINK", "FAT link removed"),
                    ("RO_FAT_LINK", "FAT link re-opened"),
                    ("RM_FAT", "FAT removed"),
                    ("CR_FAT_MAN", "Manual FAT added"),
                ],
                default="CR_FAT_LINK",
                max_length=11,
            ),
        ),
    ]
