# Generated by Django 4.0.10 on 2023-09-22 09:09

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afat", "0030_alter_log_log_event"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AaAfat",
            new_name="General",
        ),
    ]
