# Generated by Django 4.0.10 on 2023-09-22 09:15

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afat", "0031_rename_aaafat_general"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access the AFAT module"),
                    ("manage_afat", "Can manage the AFAT module"),
                    ("add_fatlink", "Can create FAT Links"),
                    ("stats_corporation_own", "Can see own corporation statistics"),
                    (
                        "stats_corporation_other",
                        "Can see statistics of other corporations",
                    ),
                    ("log_view", "Can view the modules log"),
                ),
                "verbose_name": "AFAT",
            },
        ),
    ]
