# Generated by Django 4.0.10 on 2023-09-22 09:31

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afat", "0032_alter_general_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClickAFatDuration",
            new_name="Duration",
        ),
    ]
