# Generated by Django 4.0.10 on 2023-09-22 09:32

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afat", "0033_rename_clickafatduration_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="duration",
            options={
                "default_permissions": (),
                "verbose_name": "FAT link duration",
                "verbose_name_plural": "FAT link durations",
            },
        ),
        migrations.AlterField(
            model_name="duration",
            name="fleet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duration",
                to="afat.afatlink",
            ),
        ),
    ]
