# Generated by Django 4.0.10 on 2023-09-22 09:48

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afat", "0034_alter_duration_options_alter_duration_fleet"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ManualAFat",
        ),
    ]
