# Generated by Django 4.0.10 on 2023-09-22 09:54

# Django
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("afat", "0035_delete_manualafat"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AFatLink",
            new_name="FatLink",
        ),
    ]
