# Generated by Django 4.0.10 on 2023-09-22 10:09

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("afat", "0036_rename_afatlink_fatlink"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fat",
            old_name="afatlink",
            new_name="fatlink",
        ),
        migrations.AlterUniqueTogether(
            name="fat",
            unique_together={("character", "fatlink")},
        ),
    ]
