# Generated by Django 4.0.10 on 2023-09-22 10:37

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afat", "0037_rename_afatlink_fat_fatlink_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fatlink",
            options={
                "default_permissions": (),
                "ordering": ("-created",),
                "verbose_name": "FAT Link",
                "verbose_name_plural": "FAT Links",
            },
        ),
        migrations.RenameField(
            model_name="fatlink",
            old_name="afattime",
            new_name="created",
        ),
    ]
